language: python
python: "3.7"
dist: xenial

services:
  - docker

env:
  - KAGGLE_CONFIG_DIR="${TRAVIS_BUILD_DIR}"  
  - GOOGLE_APPLICATION_CREDENTIALS="/gcs_key.json"

stages:
  - lint
  - test
  - name: release
    if: tag IS present

cache:
  paths:
    - .venv

before_install:
  - bin/check_version
  - export POETRY_VERSION="1.0.3"
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry config virtualenvs.in-project true
  - poetry install -v

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: test
      python:
        - "3.7"
        - "3.8"
      script:
        - poetry run pytest --cov=halite --cov-report term-missing tests/
        - poetry run codecov
    # - stage: release
    #   before_script:
    #     - bin/check_release "${TRAVIS_TAG}"
    #     - poetry run python bin/validate_submission.py
    #     - echo -n "${KAGGLE_API_TOKEN}" | base64 -d > kaggle.json
    #   script:
    #     - bin/submit "${TRAVIS_TAG}"
    - stage: release
      before_script:
        - bin/check_release "${TRAVIS_TAG}"
        # - poetry run python bin/validate_submission.py
        - echo -n "${GOOGLE_APPLICATION_CREDENTIALS_FILE}" | base64 -d > /gcs_key.json
      script:
        - IMAGE_TAG="${TRAVIS_REPO_SLUG}:${TRAVIS_TAG}"
        - docker build -t "${IMAGE_TAG}" -f Dockerfile .
        - bin/push_image_to_gcr "${IMAGE_TAG}"
