language: python
python: "3.7"
dist: xenial

stages:
  - check
  - lint
  - test
  - name: release
    if: tag IS present

cache:
  directories:
    - .venv

before_install:
  - bin/check_version
  - export POETRY_VERSION="1.0.3"
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry config virtualenvs.in-project true
  - poetry install -v

jobs:
  include:
    - stage: check
      name: "Version checking"
      script:
        - bin/check_version
    - stage: lint
      name: "Black linting"
      script:
        - make lint_black
    - stage: lint
      name: "Prettier linting"
      language: node_js
      node_js:
        - 12
      script:
        - make lint_prettier
      before_install: skip
      install: skip
    - stage: lint
      name: "Pylint linting"
      script:
        - make lint_pylint
    - stage: test
      name: "Pytest testing"
      python:
        - "3.7"
        - "3.8"
      script:
        - poetry run pytest --cov=halite --cov-report term-missing tests/
        - poetry run codecov
    - stage: release
      name: "Pushing to GCR"
      services:
        - docker
      env:
        - GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcs_key.json"
        - VERSION=2.0.1
        - OS=linux
        - ARCH=amd64
      before_script:
        - bin/check_release "${TRAVIS_TAG}"
        - echo -n "${GOOGLE_APPLICATION_CREDENTIALS_FILE}" | base64 -d > "${GOOGLE_APPLICATION_CREDENTIALS}"
        # https://cloud.google.com/sdk/docs/downloads-versioned-archives
        - sudo bin/install_google_cloud_sdk
        - sudo chown -R "$(whoami)" "$HOME/.config/gcloud"
        - source ./google-cloud-sdk/path.bash.inc
        - gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
        - gcloud auth configure-docker
      script:
        - IMAGE_TAG="${TRAVIS_REPO_SLUG}:${TRAVIS_TAG}"
        - docker build -t "${IMAGE_TAG}" -f Dockerfile .
        - bin/push_image_to_gcr "${IMAGE_TAG}"
      install: skip
